imerir_noyau_homepage:
    path:     /toto
    defaults: { _controller: ImerirNoyauBundle:Home:index }

imerir_noyau_userpage:
    path:    /user
    defaults: { _controller: ImerirNoyauBundle:Soap:login }