services:
    bdd_service:
        class: Imerir\NoyauBundle\Services\BDDService
        arguments: ['@service_container']
    user_service:
        class: Imerir\NoyauBundle\Services\UserService
        arguments: ['@service_container']
      